seed = 3
function = "bin.ffn.main"
n_trials = 1000
timeout = "__null__"

[sampler]

[space]
seed = 3
num_embeddings = "__null__"
batch_size = 128
patience = 16
n_epochs = inf

[space.data]
seed = 3
cache = true
path = ":data/gesture"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "__null__"

[space.model]
type = "MLP"
n_blocks = [
    "_tune_",
    "int",
    1,
    6,
]
d_layer = [
    "_tune_",
    "int",
    64,
    1024,
]
dropout = [
    "_tune_",
    "?uniform",
    0.0,
    0.0,
    0.5,
]
activation = "ReLU"

[space.optimizer]
type = "AdamW"
lr = [
    "_tune_",
    "loguniform",
    1e-05,
    0.001,
]
weight_decay = [
    "_tune_",
    "?loguniform",
    0.0,
    1e-06,
    0.0001,
]
